version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: license_scout
    versions:
    - "> 1.0"
  - dependency-name: aruba
    versions:
    - 1.0.0
