version: "{build}"

os: Windows Server 2012
platform:
  - x64

environment:
  matrix:
    - ruby_version: "200"

clone_folder: c:\projects\omnibus
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;C:\Ruby21%ruby_version:~3%\Devkit\mingw\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version
  - cp C:\Ruby21%ruby_version:~3%\Devkit\mingw\bin\bsdtar.exe C:\Ruby21%ruby_version:~3%\Devkit\mingw\bin\tar.exe

build_script:
  - bundle install

test_script:
  - bundle exec rake unit
  - bundle exec rake functional
  - bundle exec rake acceptance
